version: "3.8"
services:
  db:
    image: postgres:17.0
    hostname: ${DB_HOST}
    ports:
      - 5432:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-job:/var/lib/postgresql/data
volumes:
  db-job: